### PR TITLE
[PR] Adjusting timer shown to user according to timezone. 

### LINKED ISSUE #353: Chore: Use Timezone of Person using the `MVP`
At present the `timer.start` is the time on the `server` so when the clocks change due to daylight savings time 
the timers all start **`1 hour`** earlier than the clock of the `person` _using_ the `App`: 

image

As you can see from this screenshot, the time on my Mac is `09:42`. 
The Timer has been running for `10 mins` since `08:32` ... 
it ***`should`*** have a `timer.start` of `09:32` ... 

We need to send the **timezone** from the `client` to the `server` and adjust the `timer.start` accordingly.
So someone using the `App` (currently `MVP`) has the correct `start` & `stop` time for their timers.
For web browser based `clients` we can get "offset" from using JS: https://stackoverflow.com/a/1809974/1148249

# Todo

+ [ ] get the `timer.start` and `timer.end` from the `client` 
+ [ ] the `timer.inserted_at` will still be defined by the `server` so we have some audit-ability...
+ [ ] figure out how to test this in `Elixir`-land ... 

@LuchoTurtle please confirm this is clear - or axsk a clarifying question - by commenting on this issue. 🙏

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #353

This took much longer than expected mainly because of the strategies that I tried to employ. These are detailed in the comments below.

This PR essentially adjusts the timezone for the user on the client side and maintains UTC-based datetimes on the server to maintain consistency across all timer objects.
The client sends the timezone during the `mounting` phase and is set as a socket assign within the LiveView.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Brudda
To tackle this, I thought it would make sense to preserve the UTC in the server and only show the user the date time according to the browser’s timezone.
This entails that whenever a user updates a timer, the UTC equivalent is saved in the database.
So *between the client and the server* (inbound and outbound), there must be a conversion from UTC to the local timezone.

This `local timezone` depends on the browser and thus will eventually be sent to the liveview **from the client**.

# First strategy

Initially, to do this, I checked a few resources:
- https://elixirforum.com/t/display-datetime-in-users-timezone/45732/8
- https://elixirforum.com/t/why-use-utc-datetime-over-naive-datetime-for-ecto/32532/19
- https://elixirforum.com/t/displaying-utc-datetime-in-users-browser-timezone/2836
- https://hexdocs.pm/phoenix_live_view/js-interop.html

I realised I could use a mix of [`on_mount`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#on_mount/1) on the LiveView and **create a hook** that would be called with `on_mount`.

Inside this hook, we can use [`attach_hook`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#attach_hook/4) to try and assign this local timezone to the socket assigns list.

However, after trying several times to get this to work and pushing events from `app.js`, I realised that this operation of assigning the `local_timezone` to the socket assigns from the client was not made exactly on mount. There would be a split second where the component would be re-mounted with the socket assigns properly set.

Although this behaviour was sufficient, I felt it was incorrect. And apparently I wasn’t alone (as shown in https://thepugautomatic.com/2020/05/persistent-session-data-via-localstorage-in-phoenix-liveview/).

# Second strategy

So after spending unnecessarily amount of time for this to work, I luckily stumbled upon [`get_connected_params/1`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#get_connect_params/1). Wish I had found this earlier, because it was exactly what I needed.

Having scraped the previous method, I went with going for this on the `on_mount` function within `app_live.ex` by doing…

```elixir
hours_offset_fromUTC: get_connect_params(socket)["hours_offset_fromUTC"] || 0
```

…in the socket assigns. It worked fine.

# Why second strategy works and what went wrong

I then tried to pass this new socket assigns `hours_offset_fromUTC` to the `list_timers_changesets/1` inside the `timer.ex` so I could return the list of Timer changesets with the the updated date times (incrementing/decrementing the number of hours according to the timezone). 

However, I wasn’t able change the `data` property inside the changeset:

- Tried to use `Enum.map` and iterate over the list and change the properties manually. This didn’t work because calling the `changeset/1` function would reset the new `start` and `stop` values of the timer immediately.
- Tried to use `Map.put/3` to override these values inside the changeset. Same thing happened.
- Tried to use `Kernel.put_in/3` but didn’t work either.
- Tried to make changes programatically (https://elixirschool.com/en/lessons/ecto/changesets#adding-changes-programmatically-3) by using functions like `change/2` or adding actions and then trying to apply them by calling [`apply_changes/1`](https://hexdocs.pm/ecto/Ecto.Changeset.html#apply_changes/1) but this didn’t work because after applying the changes, the a Timer object was returned with the changes **instead of a changeset**. We need the changeset to be returned because it is used in the client-side (app_live.html.heex) to make user input validations and show correct feedback (for example, try to update a Timer with an incorrect format).

Since these weren’t working, I simply had to put some logic inside `app_live.html.heex` to show the user the correct date time and then change *back* the timezone when updating the timers.

**Comment by LuchoTurtle** [comment]
This PR is still in draft because, although everything works when I test, I can't seem to reproduce the behaviour while testing. I'm trying to have `LiveViewTest` assigning `hours_offset_fromUTC` during the unit test but it's getting ignored...

**Comment by nelsonic** [comment]
@LuchoTurtle thanks for the the detailed comments on this PR and on the issue #353 👌 
If you need to make changes to the DB please LMK by linking to a comment on `Signal` so that I can reply fast. 👍

**Comment by LuchoTurtle** [comment]
It seems my conundrum has occurred to someone else... https://elixirforum.com/t/how-do-i-test-my-liveview/39344.
No responses though :/

**Comment by LuchoTurtle** [comment]
This should be reviewable now.

**Comment by LuchoTurtle** [comment]
Hey @nelsonic, do I need to resolve the conflicts for you to review this and get this merged?

**Comment by nelsonic** [comment]
@LuchoTurtle thanks for the ping. I'm just trying to figure out something that I have a bunch of tabs/windows open for right now and will review this next. 👌

**Comment by nelsonic** [comment]
If you have a couple of mins please fix the `merge-conflicts` and re-assign. 🙏

**Comment by LuchoTurtle** [comment]
@nelsonic should be mergeable now 👌

**Comment by nelsonic** [comment]
https://everytimezone.com
every timezone


image

image

**Comment by nelsonic** [comment]
Sorry didn't mean to _close_ the PR. 🤦‍♂️ Just wanted to include those screenshots as a comment.

**Comment by nelsonic** [comment]
@LuchoTurtle for future reference (not just on @dwyl projects ...),
the PR is not reviewable if the CI checks aren't passing. 

image

In this case it's the **`Review App`** that is failing: 
https://github.com/dwyl/mvp/actions/runs/5023363276/jobs/9015775607#step:5:1493

image

Looks like we need a `tech-debt` issue for this: https://github.com/dwyl/mvp/issues/373

**Review by nelsonic — APPROVED** [review]
@LuchoTurtle this _appears_ to work when I test it on `localhost`. 👍 
But I don't have multiple devices in different timezones so I cannot QA edge cases. 🧑‍💻 📱  🤷‍♂️ 
I vote that we _merge_ it :shipit:  and then when someone in `NZ` tests it we can get their feedback and improve as needed. 👌

**Comment by LuchoTurtle** [comment]
I *never* submit for review without checking the action status. When I pushed for review, 100% it was passing, or else I'd get an email saying it wasn't. I don't know if it stopped working because of other commits being made to the `main` branch that re-ran the actions here and made them fail but they were passing when I made the commit, especially after `mix format` commit

**Pull request merged**
