### PR TITLE
PR: move selected `tags` above `tags` selector #296

### PR DESCRIPTION
**Pull request by nelsonic**
+ [x] Fixes the bug noted in #296 where the tag selector covers the selected tags.

### CODE REVIEW

**Comment by nelsonic** [comment]
Review app working: https://mvp-pr-298.fly.dev/
image

**Comment by nelsonic** [comment]
This PR is dependent on fixing #297 ⏳ 
@LuchoTurtle please investigate when you can. 🙏

**Comment by nelsonic** [comment]
@seaneady please approve & merge when you can. 🙏

**Review by seaneady — APPROVED** [review]
Everything looks good here 👍

**Comment by nelsonic** [comment]
Sweet. thanks for pairing and merging this. 🚀

**Pull request merged**
