### PR TITLE
[PR] Adding Papertrail and recording changes

### LINKED ISSUE #252: Feat: Add `PaperTrail` to MVP to enable `item.text` History!
The outcome of our `PaperTrail` learning [`SPIKE`] was successful: https://github.com/dwyl/phoenix-papertrail-demo
We need to outline how we are going to apply it to the `MVP` so that we can capture versions of `item.text`
so that there is a full history of the changes made to the `item`. 👍 

# Todo

@LuchoTurtle given that you have the most knowledge in the team of this, please:

+ [x] Outline how the DB Table Schema will change following the introduction of `PaperTrail` [please comment below!]
+ [x] Document all the steps to add `PaperTrail` in `buildit.md`, but link to the [dwyl/phoenix-papertrail-demo](https://github.com/dwyl/phoenix-papertrail-demo) for the "boilerplate" parts.
+ [x] Implement it with tests. 
+ [ ] Showcase it tomorrow at standup. 😉 

Don't worry, not asking you to implement the UI/UX for this, _yet_ ... just the backend! 👌

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #252 

Integrates `PaperTrail` to track changes when updating/inserting `items`.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Guess the `People` table is a no-go https://github.com/dwyl/mvp/pull/250#discussion_r1065757858
Gonna change this tomorrow.

**Comment by nelsonic** [comment]
@LuchoTurtle indeed. `people` table was removed in https://github.com/dwyl/mvp/issues/118 ✅ 
Please `rebase` on `main` and it should be good to go. 👌

**Comment by LuchoTurtle** [comment]
@nelsonic should be mergeable.
The reason "the coverage dropped" is because of the "bug" of formatting that also occurs in https://github.com/dwyl/mvp/pull/246#issuecomment-1370926216 😦

**Comment by nelsonic** [comment]
Will take a look at this one _next_. 👌

**Review by nelsonic — APPROVED** [review]
@LuchoTurtle looks good. Thanks! 👌

**Pull request merged**
