### PR TITLE
Call resize() on x:init

### PR DESCRIPTION
**Pull request by SimonLab**
Make sure the textarea is properly resized
when the text draft is saved

see: #305

### CODE REVIEW

**Comment by SimonLab** [comment]
flyctl command failed to installed for the review app:
> curl: (3) URL using bad/illegal format or missing URL

It might have been the url down for a bit maybe.
I don't think this is a blocker for this PR

**Review by LuchoTurtle — APPROVED** [review]

**Comment by LuchoTurtle** [comment]
Seems to be working for me! 

image

**Comment by nelsonic** [comment]
@SimonLab ping me when the **`Review App`** deploys. will test it on Fly.io then merge. 👌

**Comment by LuchoTurtle** [comment]
@nelsonic it's deployed 
https://github.com/dwyl/mvp/actions/runs/4173810683/jobs/7227241749

**Comment by SimonLab** [comment]
@nelsonic thanks for rerun the review app script.
This is now available at https://mvp-pr-306.fly.dev/ to test

**Review by nelsonic — APPROVED** [review]
LGTM! 👍 
image

**Pull request merged**
