### PR TITLE
Create new Github Action for review apps

### PR DESCRIPTION
**Pull request by SimonLab**
Create new Github action file to create review apps

### CODE REVIEW

**Comment by SimonLab** [comment]
Creating review app failed:
image

I can see a few issues already
From https://github.com/marketplace/actions/pr-review-apps-on-fly-io
> By default, Fly apps will be named with the scheme pr-{number}-{repo_org}-{repo_name}.

However the name is `pr-229-null-null` So the org_name and repo_name is not found/set properly 

Then `mix not found in path`. I might need to copy more things from our working Github action to install Elixir and Phoenix first.

**Comment by SimonLab** [comment]
After looking at the code in https://github.com/superfly/fly-pr-review-apps/blob/main/entrypoint.sh I think the `attach postgres` is not up to date with the latest flyctl version (ex: the --postgres-app flag has been removed).
I'm going to do some manual test and try to deploy multiple Phoenix application connected to the same Postgres cluster.
If this work I'll be able to add the specific `flyctl` commands we want to run in our Github action.

**Comment by nelsonic** [comment]
Good plan. Hope it works. 🤞

**Comment by SimonLab** [comment]
I've managed to create manually using the `flyctl` commands a review app and attach the current database to this new app.
I've also managed to create a Github action that can run a bash script which use the flyctl command. I had a few blockers while doing this so I'll write a bit of documentation on how to do this.
I'm now able to create the full script to have review apps created/removed when a PR is open/closed. I just need a bit of time to make sure I have all the edge cases cover (PR is updated -> redeploy, do not create review app when main branch is updated...)

**Comment by SimonLab** [comment]
Closing in favour of #230

**Pull request closed without merging**
