### PR TITLE
[PR] Upgrading to Node16 and temporarily disabling `Review App` and `API Definition` tests

### LINKED ISSUE #404: Chore: Update Node.js Version to `v20` used for API tests
https://github.com/dwyl/mvp/actions/runs/5856288034?pr=345
mvp-node-version-for-api-tests

```sh
The following actions uses node12 which is deprecated 
and will be forced to run on node16: actions/checkout@v2. 
For more info: 
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

# Todo

+ [ ] Red the changelog: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
+ [ ] Make any required updates
+ [ ] Create PR
+ [ ] Assign for review
+ [ ] Confirm working once merged.

### LINKED ISSUE #406: chore: `useful` 1.12 upgrade introduced `Plug.Upload.__struct__/0 is undefined` error
We're getting this error when compiling the app.

```
Error: ** (CompileError) lib/useful.ex:24: Plug.Upload.__struct__/0 is undefined, cannot expand struct Plug.Upload. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code

```

This is due to a release made from https://github.com/dwyl/useful 4 days ago. This is causing the `Review App` job to crash, subsequently not allowing other checks to be made.

https://github.com/dwyl/mvp/actions/runs/5860010329?pr=405

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #404 
closes #406 

Additionally, it upgrades the `mix.lock` file, thus fixing the compilation error when running `flyctl` (related to the `useful` package).

This also temporarily disabled the `Review App` and `API Definition` Github Action pipelines due to https://github.com/dwyl/mvp/issues/407

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
I've seen this error popped up ever since `useful` was upgraded. I've tried circumventing it and it appears to have been related with the release that occurred 4 days ago.

```
Error: ** (CompileError) lib/useful.ex:24: Plug.Upload.__struct__/0 is undefined, cannot expand struct Plug.Upload. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
```

I'm opening an issue on this. Easy route would be to revert this upgrade but I wager we'll have to check what's going on in https://github.com/dwyl/useful.

**Comment by nelsonic** [comment]
I find it _very_ peculiar that we're getting this `Plug.Upload undefined` error when `Plug` is in the `mix.lock` file: 

https://github.com/dwyl/mvp/blob/4c0639a5bbf9b344d1e8683edcd6bd46e825748f/mix.lock#L56

`Plug.Upload` is just a module in:  https://github.com/elixir-plug/plug/blob/v1.14.2/lib/plug/upload.ex#L5

**Comment by nelsonic** [comment]
Review App Script failed: https://github.com/dwyl/mvp/actions/runs/5864562055/job/15899841640?pr=405 🤷‍♂️ 
image

Re-running ... ♻️

**Comment by nelsonic** [comment]
Review App fails: https://github.com/dwyl/mvp/issues/407

**Comment by nelsonic** [comment]
@LuchoTurtle given that the build is passing (with Review Apps disabled) feel free to assign for review + merge.
As noted in #407 I think that the `deploy` from `GitHub` in the Review Apps script issue is out of our control ...
If other people are having the same issue: https://github.com/dwyl/mvp/issues/407#issuecomment-1678573478
We should not spend any more time on this _today_.
Rather we should check back on the Fly.io forum in a few days time and see if anyone has figured it out. 🤞

**Comment by LuchoTurtle** [comment]
@nelsonic this should be good to go. 👌

**Review by nelsonic — APPROVED** [review]
@LuchoTurtle looks good. thanks. 🙏

**Pull request merged**
