### PR TITLE
[PR] Reactivating Review Apps to check if it works.

### LINKED ISSUE #407: Chore: Error: release command failed - aborting deployment [Review Apps]
Seeing the following error on the #405 PR:
https://github.com/dwyl/mvp/actions/runs/5864648540/job/15900061668#step:5:1515
image

```sh
  2023/08/15 07:22:30 listening on [fdaa:0:78d4:a7b:173:9fb5:5989:2]:22 (DNS: [fdaa::3]:53)
  [    2.316331] reboot: Restarting system
  machine restart policy set to 'no', not restarting
Error: release command failed - aborting deployment. 
error release_command machine 784e677f2265d8 exited with non-zero status of 1
```

# Todo

+ [ ] Investigate how to avoid this issue ... 🔍 
https://www.google.com/search?q=fly.io+machine+restart+policy+set+to+%27no 
https://community.fly.io/t/how-do-i-change-the-restart-policy-for-machines/7341/2 Inconclusive ... 
https://community.fly.io/t/i-am-getting-release-command-failed/14775 [Unresolved!]

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #407 

Reactivating the `Review Apps` and `API definition` tests to see if it's properly working again.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
🤔 weird. I'm running the commands within the `Review App` on my local machine in a sequential fashion and it seems to deploy properly

image

**Comment by nelsonic** [comment]
@LuchoTurtle the biggest issue with review apps isn't even the deployment ... 
it's the fact that `WebSockets` don't work on the review app which means `LiveView` is useless.

**Comment by LuchoTurtle** [comment]
@nelsonic that wasn't detailed in the aforementioned issue, hence why I tried to open this PR. But it's a fruitless pursuit, might as well close this one off.

**Comment by nelsonic** [comment]
I don't mean you should close it. Sorry if that was unclear. I would _love_ Review Apps to work seamlessly. 🙏

**Pull request closed without merging**
