### PR TITLE
Run mix format

### PR DESCRIPTION
**Pull request by SimonLab**
Fix format error on `router.ex`

ref: https://github.com/dwyl/mvp/issues/183#issuecomment-1285160054

### CODE REVIEW

**Comment by SimonLab** [comment]
The codecov project status is failing because the empty line as been removed:
image

I don't think this report is useful on this PR

**Review by nelsonic — APPROVED** [review]
@SimonLab am I right in thinking this PR just adds whitespace? 🤷‍♂️

**Comment by nelsonic** [comment]
Very bizarre that this is lowering coverage ... 🤷‍♂️

**Comment by nelsonic** [comment]
@SimonLab thanks for confirming. Merging. ✅

**Pull request merged**
