### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by SimonLab**
Update dependencies.
Use override on envar to avoid conflicts with fields

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab feel free to apply this change to #227 if it passes, merge. 👌

**Comment by SimonLab** [comment]
I wasn't sure if you wanted to add more things to #227 that's why I've opened this one. I'll add the change to the PR and close this one.

**Comment by SimonLab** [comment]
closing in favour of #227

**Comment by nelsonic** [comment]
Yeah, I didn't _want_ to open a `deps ### update` PR at all. I just opened it cause build was failing on `main` ...

**Pull request closed without merging**
