### PR TITLE
PR: Update `deps`

### PR DESCRIPTION
**Pull request by nelsonic**
This PR will only pass once all the `deps` are updated. I will assign when ready.

### CODE REVIEW

**Comment by nelsonic** [comment]
Side-quest: https://github.com/dwyl/logs/issues/1

**Comment by SimonLab** [comment]
Conflicts for the envar and fields dependencies:
image

I also have the following error after getting the latest version from main:
image

I'll try to update auth_plug only to have a stable version running

**Comment by nelsonic** [comment]
Yeah, I know right ... 🙄 🤦‍♂️ 
Please help investigate: https://github.com/dwyl/hits/issues/203 🙏

**Comment by SimonLab** [comment]
I've arrived at the same step as you, I had to update envar then fields. I'm wondering if it's not an issue with hex packages not being available (cdn broken?).
I'm not sure the hits issue is the same as this one however

**Comment by nelsonic** [comment]
Nah, this is just a deps mismatch. It will all be resolved shortly. I'm just writing up on my side. happy to screen-share if you want to pair. But otherwise please look at the issue above (get Hits working) 🙏

**Comment by SimonLab** [comment]
Removing empty line push down the coverage:
image

But otherwise the dependencies conflict are now resolved.
@nelsonic merging this one now should allow #225 to be deployed now

**Comment by nelsonic** [comment]
@SimonLab If you're happy to merge, please go for it. 👌

**Review by SimonLab — APPROVED** [review]
LGTM

**Comment by SimonLab** [comment]
Latest closed PR deployed on Fly!

**Pull request merged**
