### PR TITLE
[PR] Upgrading to Phoenix 1.7

### LINKED ISSUE #322: Chore: Update MVP to `Phoenix 1.7`
With the release of `Phoenix 1.7` over the weekend: https://phoenixframework.org/blog/phoenix-1.7-final-released 🎉 
Now is a great time to update our `MVP` to the latest and greatest. 👌 

@LuchoTurtle, as discussed on Standup if you want to pick this up, please go for it. 🙏

+ [x] Update the project to `Phoenix 1.7` 📝 
+ [x] remove any code that is no longer needed ✂️ 
+ [x] remove/update the Tailwind section in `BUILDIT.md`: https://github.com/dwyl/mvp/blob/main/BUILDIT.md#13-setup-tailwind
+ [x] create a PR & assign for review

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #322 

This PR upgrades the project to Phoenix 1.7.

Following https://gist.github.com/chrismccord/00a6ea2a96bc57df0cce526bd20af8a7.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Getting the following error.

```
== Compilation error in file lib/app_web/live/stats_live.ex ==
** (CompileError) lib/app_web/live/stats_live.ex:3: module Phoenix.View is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
    expanding macro: AppWeb.__using__/1
    lib/app_web/live/stats_live.ex:3: AppWeb.StatsLive (module)
    (elixir 1.14.3) expanding macro: Kernel.use/2
```

Might have to replace occurrences with `Phoenix.Template` 🤔

**Comment by LuchoTurtle** [comment]
I am, I mentioned it in the PR

**Comment by nelsonic** [comment]
@LuchoTurtle just did the update on https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/pull/31/files and it works well. ✅

**Comment by nelsonic** [comment]
I'm not offended by the addition of:

```elixir
{:phoenix_view, "~> 2.0"},
```
To the `mix.exs -> deps` to avoid as many updates.

**Comment by LuchoTurtle** [comment]
I didn't want to follow https://elixirforum.com/t/module-phoenix-view-is-not-loaded-and-could-not-be-found/52362 and add the `{:phoenix_view, "~> 2.0"},` dependency, but since @nelsonic stated that it was ok, I went for it. I fixed some warnings that came with this upgrade as well.

I initially wanted to do a more thorough upgrade, removing the soft-deprecated helpers and making full use of verified routes. But since it is intended to be an upgrade without many changes, I'll leave it at here.

**Review by nelsonic — APPROVED** [review]
Thanks @LuchoTurtle looks good. 👍

**Pull request merged**
