### PR TITLE
PR: Create Review Apps

### PR DESCRIPTION
**Pull request by SimonLab**
Start documentation on how to create a Github action for review apps

### CODE REVIEW

**Comment by SimonLab** [comment]
So I think the script to deploy a new Fly appication when a PR is created works. It creates a new application names: `mvp-pr-#<pr-number>.
However I don't think the script can work for application using `auth`: I've added the `AUTH_API_KEY` as environment variables (copied from the mvp app) but this api key is unique to the `mvp` name and doesn't work fro `mvp-pr-...` names:

image

For this to work, a new api key on auth needs to be created manually providing the correct url name:
image


So to conclude I don't think we can have an automatic way of creating review apps.
Let me know if this makes sense @nelsonic and if you have other idea to resolve this, but I don't think it's possible at this stage. 

We can create one `mvp-review-app` application manually and deploy PRs manually to this application if we want to showcase the new code

**Comment by SimonLab** [comment]
I have a similar issue to https://community.fly.io/t/postgres-lingering-connection-after-deleting-fly-app/4771/3

I've deleted manually the review apps while testing the script. The database created by the script is not deleted and I'm now blocked when attempting to run `flyctl postgres attach`. The command fails (as the db already exists) and the `DATABASE_URL` is not set which break the deployement.

**Comment by SimonLab** [comment]
The script for deploying review apps is now ready, see https://mvp-pr-230.fly.dev/ for this current PR.
I haven't tried yet to check the review app is removed when a PR is merged but this can be tested once this PR is merged.

**Review by nelsonic — APPROVED** [review]
Looks great. Thanks @SimonLab 👍

**Comment by nelsonic** [comment]
@SimonLab Could you please confirm that the review app is deleted automatically when no longer needed?

https://mvp-pr-230.fly.dev/
image

**Comment by SimonLab** [comment]
The action has been triggered by the "closed" event when the PR has been merged and the script to "destroy" the application exited without error:
image

On the Fly dasbhoard the `mvp-pr-230` has been removed:
image

**Pull request merged**
