### PR TITLE
PR: Create migration to change `item.text` type from `string` to `text`

### PR DESCRIPTION
**Pull request by SimonLab**
Update type for item's text
ref: #204

### CODE REVIEW

**Comment by nelsonic** [comment]
Does this line also need to be updated: ?

https://github.com/dwyl/mvp/blob/f5bd6f1880378260091de62fa7528f8753649cb9/lib/app/item.ex#L10

**Comment by SimonLab** [comment]
> Does this line also need to be updated: ?

No the schema doesn't have the `text` type:

https://hexdocs.pm/ecto/Ecto.Schema.html#module-primitive-types

> Ecto type may support multiple database types. For example, all of :varchar, :text, :bytea, etc.

**Comment by nelsonic** [comment]
Right, so `Ecto` doesn't differentiate between `String` and `Text` but the underlying `Postgres` Table/Column does. 👌

**Review by nelsonic — APPROVED** [review]
Thanks @SimonLab 👌

**Pull request merged**
